# Generated by Django 2.2 on 2020-02-26 11:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewEntry',
            fields=[
                ('record_id', models.IntegerField(auto_created=True, unique=True, verbose_name='Record Id')),
                ('document_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('received_on', models.DateField(auto_now_add=True)),
                ('entry_class', models.CharField(choices=[('incoming', 'Outgoing Documents'), ('outgoing', 'Incoming Documents'), ('document_within', 'Document Within')], max_length=20)),
                ('document_title', models.CharField(max_length=250)),
                ('created_on', models.DateField(auto_now=True)),
                ('document_type', models.CharField(choices=[('forms', 'Forms'), ('memo', 'Memo'), ('reports', 'Reports'), ('letter', 'Letter'), ('envelop', 'Envelope')], max_length=10, verbose_name='Document Type')),
                ('doc_sender', models.CharField(max_length=250, verbose_name='Sender name and designation')),
                ('sender_thru', models.CharField(max_length=250, verbose_name='Sender thru name and designation')),
                ('doc_receiver', models.CharField(max_length=250, verbose_name='Receiver name and designation')),
                ('doc_source', models.CharField(max_length=250, verbose_name='Source of document/Department/Unit')),
                ('doc_destination', models.CharField(max_length=250, verbose_name='Destination of document/Department/Unit')),
                ('comment', models.TextField()),
            ],
        ),
    ]
