# Generated by Django 2.2 on 2020-02-26 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docRecords', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newentry',
            name='document_type',
            field=models.CharField(choices=[('forms', 'Forms'), ('memo', 'Memo'), ('reports', 'Reports'), ('letter', 'Letter'), ('envelope', 'Envelope')], max_length=10, verbose_name='Document Type'),
        ),
    ]
