# Generated by Django 2.2 on 2020-02-28 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docRecords', '0002_auto_20200226_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newentry',
            name='record_id',
        ),
        migrations.AddField(
            model_name='newentry',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
