# Generated by Django 2.2 on 2020-02-28 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docRecords', '0003_auto_20200228_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newentry',
            name='doc_destination',
            field=models.CharField(max_length=250, verbose_name='Destination of Document/Department/Unit'),
        ),
        migrations.AlterField(
            model_name='newentry',
            name='doc_receiver',
            field=models.CharField(max_length=250, verbose_name='Receiver name:Designation'),
        ),
        migrations.AlterField(
            model_name='newentry',
            name='doc_sender',
            field=models.CharField(max_length=250, verbose_name='Sender name:Designation'),
        ),
        migrations.AlterField(
            model_name='newentry',
            name='doc_source',
            field=models.CharField(max_length=250, verbose_name='Source of Document/Department/Unit'),
        ),
        migrations.AlterField(
            model_name='newentry',
            name='document_type',
            field=models.CharField(choices=[('forms', 'Forms'), ('memo', 'Memo'), ('reports', 'Reports'), ('letter', 'Letter'), ('envelope', 'Envelope'), ('cv', 'CV'), ('proposal', 'Proposal')], max_length=20, verbose_name='Document Type'),
        ),
        migrations.AlterField(
            model_name='newentry',
            name='sender_thru',
            field=models.CharField(max_length=250, verbose_name='Sender name Thru:Designation'),
        ),
    ]
