# Generated by Django 2.2 on 2020-03-02 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docRecords', '0004_auto_20200228_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newentry',
            name='document_type',
            field=models.CharField(choices=[('Forms', 'Forms'), ('Memo', 'Memo'), ('Reports', 'Reports'), ('Letter', 'Letter'), ('Envelope', 'Envelope'), ('CV', 'CV'), ('Proposal', 'Proposal')], max_length=20, verbose_name='Document Type'),
        ),
        migrations.AlterField(
            model_name='newentry',
            name='entry_class',
            field=models.CharField(choices=[('Incoming Documents', 'Incoming Documents'), ('Outgoing Documents', 'Incoming Documents'), ('Documents Within', 'Documents Within')], max_length=30),
        ),
    ]
